### ISSUE TITLE
远程支付站点发生问题，或创建订单的地址有误http://www.xx.com/CreateOrder

### ISSUE THREAD

**Issue by 2100709717** [Vpay-Collection/VPay#48]
远程支付站点发生问题，或创建订单的地址有误http://www.xx.com/CreateOrder

**Comment by yyyyy1412** [comment]
这个问题有解决的吗 ？

**Comment by dreamncn** [comment]
这个是你服务器的问题



---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年11月22日(周一) 晚上6:34
收件人: ***@***.***&gt;;
抄送: ***@***.***&gt;;
主题: Re: [dreamncn/VPay] 远程支付站点发生问题，或创建订单的地址有误http://www.xx.com/CreateOrder (#48)




 
这个问题有解决的吗 ？
 
—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by dreamncn** [comment]
2.0已经弃更，欢迎尝鲜[3.0](https://github.com/dreamncn/VPay/releases/tag/3.0)
